#:schema node_modules/wrangler/config-schema.json
name = "waha-agent-cf"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# 环境变量（敏感信息通过 wrangler secret 设置）
[vars]
ENVIRONMENT = "development"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "waha-agent"
database_id = "your-database-id"  # 部署时需要替换
migrations_dir = "database/migrations"

# 本地开发数据库
[[d1_databases]]
binding = "DB_LOCAL"
database_name = "waha-agent-local"
database_id = "local"

# KV 命名空间
[[kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"  # 部署时需要替换
preview_id = "your-preview-kv-id"

# R2 存储桶
[[r2_buckets]]
binding = "R2"
bucket_name = "waha-agent-storage"
preview_bucket_name = "waha-agent-storage-preview"

# Vectorize 索引
[[vectorize]]
binding = "VECTORIZE"
index_name = "waha-agent-vectors"

# Durable Objects - T016 Message Merging System
[[durable_objects.bindings]]
name = "CHAT_SESSIONS"  
class_name = "ChatSessionDO"
script_name = "waha-agent-cf"

# Durable Objects Migrations  
[[migrations]]
tag = "v1"
new_classes = ["ChatSessionDO"]

# 队列
[[queues.producers]]
binding = "QUEUE_RETRIEVE"
queue = "waha-agent-retrieve"

[[queues.producers]]
binding = "QUEUE_INFER" 
queue = "waha-agent-infer"

[[queues.producers]]
binding = "QUEUE_REPLY"
queue = "waha-agent-reply"

[[queues.producers]]
binding = "QUEUE_EMBED"
queue = "waha-agent-embed"

# 队列消费者
[[queues.consumers]]
queue = "waha-agent-retrieve"
max_batch_size = 10
max_batch_timeout = 5

[[queues.consumers]]
queue = "waha-agent-infer"
max_batch_size = 5
max_batch_timeout = 5

[[queues.consumers]]
queue = "waha-agent-reply"
max_batch_size = 5
max_batch_timeout = 5

[[queues.consumers]]
queue = "waha-agent-embed"
max_batch_size = 10
max_batch_timeout = 5

# 环境配置
[env.staging]
name = "waha-agent-cf-staging"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "waha-agent-cf-production"
vars = { ENVIRONMENT = "production" }

# 部署配置
[build]
command = "bun run build:backend"

# 限制配置
[limits]
cpu_ms = 30000